![alt text](./assets/pandas_logo.jpg)



## Introduction to pandas

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

## What is Pandas?

Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.


## Installing Pandas

When you want to work with pandas locally, you should run the following commands:

`pip install pandas`\
or\
`conda install pandas`

In our case, 4Geeks have prepared all the environment in order that you can work comfortably.



## Why use Pandas?

Pandas allows us to analyze big data and make conclusions based on statistical theories. It can clean messy data sets, and make them readable and relevant and clearly, relevant data is very important in data science.

But the main reason is Pandas allow you deal with a new structure of data: dataframes. A dataframe is a two-dimensional data structure in which data of different types (such as characters, integers, floating-point values, factors, and more) can be stored in columns. It is similar to an SQL spreadsheet or table of excels. A dataframe always has an index (starting at 0). The index refers to the position of an element in the data structure.

Pandas provides tools that allow:

- read and write data in different formats: CSV, Microsoft Excel, SQL databases and HDF5 format

- easily select and filter data tables based on position, value, or labels

- merge and join data

- time series manipulation

- make graphs (plots)

In pandas there are three basic types of objects, all of them based on Numpy:

- Series (lists, 1D),

- DataFrame (tables, 2D) and

- Panels (3D tables).

#### Exercise: Import the pandas package under the name `pd` (★☆☆)

To import a new library in python we have to use the import statement like this: `import <library_name> as <your_alias>`.

Use the `import` statement in python to import the pandas module under the alias pd. If you want to assert the library was correctly imported, remember you can print the version of any python library with: `name_of_package.__version__`

In [2]:
import pandas as pd

## Pandas data types

Pandas has three different data structures:

- Series: One-dimensional structure.
- DataFrame: Two-dimensional structure (tables).
- Panel: Three-dimensional structure (cubes and less used).

These structures are built from arrays from the NumPy library, adding new functionalities.


<img src="./assets/series_dataframe.png" width="600"/>


## Object creation

Creating a Series by passing a list of values, letting pandas create a default integer index:

In [4]:
import numpy as np
import pandas as pd

s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In the previous exercise, we have created a pandas series (a one-dimensional vector or array) from a list. In the following exercise, we ask you to create a one-dimensional vector but this time from other python structures.

#### Exercise: Create a pandas series from each of the items below: a list, numpy and a dictionary (★☆☆)

In [14]:
import pandas as pd
import numpy as np

s = pd.Series([[1,3],np.ones(2),{'p1':(1,4)}])

print(s)

0            [1, 3]
1        [1.0, 1.0]
2    {'p1': (1, 4)}
dtype: object


#### Exercise: Now, try to create a dataframe of one column from a pandas series (★☆☆)

Check the function `to_frame` (https://pandas.pydata.org/docs/reference/api/pandas.Series.to_frame.html)

In [19]:
import numpy as np
import pandas as pd

s = pd.Series(np.random.randint(0,10,5),name='random_ints')
print(s)

print(s.to_frame())

0    9
1    0
2    6
3    8
4    7
Name: random_ints, dtype: int64
   random_ints
0            9
1            0
2            6
3            8
4            7


#### Exercise: How to combine many series to form a dataframe? (★☆☆)
Create two series with names `ser1` and `ser2` to form a dataframe. That is, a two columns dataframe from the series `ser1` and `ser2`.

In [25]:
import numpy as np
import pandas as pd

ser1 = pd.Series(np.random.randint(0,10,3), name='r1')
ser2 = pd.Series(np.random.randint(0,10,3),name='r2')

print(ser1)
print(ser2)

df = pd.concat([ser1,ser2,pd.Series(['a','b','c'],name='L')],axis=1)

print(df)



0    1
1    8
2    8
Name: r1, dtype: int64
0    8
1    6
2    0
Name: r2, dtype: int64
   r1  r2  L
0   1   8  a
1   8   6  b
2   8   0  c


#### Exercise: How to get the items not common to both series A and series B? (★☆☆)
Extract the elements that are not in common of the series `ser1` and `ser2`we define below.
Check functions `union1d` and `intersect1d` from numpy. Yes, numpy (https://numpy.org/doc/stable/reference/generated/numpy.union1d.html and https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html). Remember that **numpy and pandas work together**

In [50]:
# Input
import numpy as np
import pandas as pd

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([3, 4, 5, 6, 7]) 

union = np.union1d(ser1,ser2)
intersect = np.intersect1d(ser1,ser2)

print(union)
print(intersect)
print(union[np.isin(union,intersect)==False])


[1 2 3 4 5 6 7]
[3 4 5]
[1 2 6 7]


#### Exercise: How to convert a numpy array to a dataframe of given shape? (★☆☆)
Reshape a random series into a dataframe with 7 rows and 5 columns. In this exercise, you have to create a one-dimensional array of length 35 and then you will have to convert that array into a dataframe

In [80]:
import numpy as np
import pandas as pd

v = np.random.randint(0,50,35)
print(v)

s = pd.Series(v,name='values')
x = s.values

#print(x.reshape((7,5)))


df1 = pd.DataFrame({'c1':s})
df2 = pd.DataFrame(x.reshape((7,5)),columns=['c1','c2','c3','c4','c5'])

print(df1)
print(df2)

[24 20 37 22 33 45 30 18 34 36 15 23 33 16 15 35 45 49 30 48 25 40 16 10
 34 41 40 34 33  1 36 33 40  7 27]
    c1
0   24
1   20
2   37
3   22
4   33
5   45
6   30
7   18
8   34
9   36
10  15
11  23
12  33
13  16
14  15
15  35
16  45
17  49
18  30
19  48
20  25
21  40
22  16
23  10
24  34
25  41
26  40
27  34
28  33
29   1
30  36
31  33
32  40
33   7
34  27
   c1  c2  c3  c4  c5
0  24  20  37  22  33
1  45  30  18  34  36
2  15  23  33  16  15
3  35  45  49  30  48
4  25  40  16  10  34
5  41  40  34  33   1
6  36  33  40   7  27


#### Exercise:  How to extract items at given positions from a series (★☆☆)
You can also create series and dataframe that contain strings. From the following pandas series `ser`, extract the items at positions in the list `pos`. Check `take`from pandas (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.take.html)

In [14]:
# Input
import pandas as pd

ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
#print(ser)
pos = [0, 4, 8, 14, 20]

df = pd.DataFrame(ser,columns=['L'])
print(df.take(pos))


    L
0   a
4   e
8   i
14  o
20  u


#### Exercise:  How to stack two series vertically and horizontally ?
Create two series `ser1` and `ser2` and stack them vertically and horizontally (to form a dataframe). Check `concatenate`from pandas (https://pandas.pydata.org/docs/reference/api/pandas.concat.html)

In [24]:
import numpy as np
import pandas as pd

x = np.random.randint(0,10,3)
y = np.random.randint(0,10,3)

print(x,y)

ser1 = pd.Series(x)
ser2 = pd.Series(y)

print(ser1)
print(ser2)
df1 = pd.concat([ser1,ser2],axis=0)
print(df1)
df2 = pd.concat([ser1,ser2],axis=1)
print(df2)

[1 4 8] [9 9 7]
0    1
1    4
2    8
dtype: int64
0    9
1    9
2    7
dtype: int64
0    1
1    4
2    8
0    9
1    9
2    7
dtype: int64
   0  1
0  1  9
1  4  9
2  8  7


#### Exercise: How to get the positions of items of series A in another series B? (★★☆)
Get the positions of items of ser2 in ser1 as a list. Remember the function `where`from numpy (https://numpy.org/devdocs/reference/generated/numpy.where.html)

In [47]:
## Input
import pandas as pd
import numpy as np

ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13]) 

i = [pd.Index(ser1).get_loc(x) for x in ser2]
print(i)

[5, 4, 0, 8]


#### Exercise: How to compute difference of differences between consequtive numbers of a series? (★★☆)
Difference of differences between the consequtive numbers of `ser`.

In [50]:
## Input
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

print(ser.diff().diff())

## Output should be like following
# [nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
# [nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]

0    NaN
1    NaN
2    1.0
3    1.0
4    1.0
5    1.0
6    0.0
7    2.0
dtype: float64


## Apply functions to a series
It is also possible to apply a function to each element of the series using the following method:

`s.apply(f)`: Returns a series with the result of applying the function f to each of the elements of the series s.

### Example
```
import pandas as pd
from math import log
s = pd.Series([1, 2, 3, 4])
s.apply(log)
```

#### Exercise: Convert all values of a pandas series of string to upper (★☆☆)
You have to create a series of strings with random values and then convert each string to capital letters.
Check upper in pandas (https://pandas.pydata.org/docs/reference/api/pandas.Series.str.upper.html)

#### Exercise: Get all values greater than 5 from a pandas series (★☆☆)
Remember that you can create series and dataframes from dictionaries. In this exercise you will have to get all values greater than 5.

In [ ]:
## Input
s = pd.Series({'Math': 6.0,  'Economy': 4.5, 'Programming': 8.5})

#### Exercise: Sort a series. Sort the series from the previous exercise in both, ascending and descendant order (★ ☆☆)
The following methods are used to sort a series:

`s.sort_values (ascending = Boolean)`: Returns the series that results from ordering the values in the series s. If the argument of the ascending parameter is True the order is increasing and if False it is decreasing.

`df.sort_index (ascending = Boolean)`: Returns the series that results from sorting the index of the series s. If the argument of the ascending parameter is True the order is increasing and if it is False decreasing.

#### Exercise: Eliminate the unknown (`NA`) values in a series.  Drop the NAs values from the series
Unknown data is represented in Pandas by `NaN` and `null` by `None`. Both are usually a problem when performing some data analysis, so it is common to eliminate them. To remove them from a series the following method is used:

s.dropna (): Removes the unknown or null data from the s series.

In [ ]:
## Input
import pandas as pd
import numpy as np
s = pd.Series(['a', 'b', None, 'c', np.NaN,  'd'])

## The DataFrame object class

An object of type DataFrame defines a set of data structured in the form of a table where each column is an object of type Series, that is, all the data in the same column are of the same type, and the rows are records that can contain data from Different types.

A DataFrame contains two indexes, one for the rows and one for the columns, and its elements can be accessed by the names of the rows and columns.

Example. The following DataFrame contains information about the students in a course. Each row corresponds to a student and each column to a variable.

![alt text](./assets/df.png "df")


## Creating a DataFrame from a CSV or Excel file
Depending on the type of file, there are different functions to import a DataFrame from a file.

- read_csv: Returns an object of type DataFrame with the data from the CSV file file.csv using as separator of the data the string separator.

- read_excel: Returns an object of type DataFrame with the data from the spreadsheet sheet of the Excel file file .xlsx.

## The Titanic dataset 
The titanica dataset is a famous and "funny" dataset in the area of data science. It is commonly used for beginners in order to know how to fit a machine learning model. The competition is simple: use machine learning to create a model that predicts which passengers survived the Titanic shipwreck.

The dataset consists of the following variables.


| Variable | Definition                                 | Key                                            |
|----------|--------------------------------------------|------------------------------------------------|
| survival | Survival                                   | 0 = No, 1 = Yes                                |
| pclass   | Ticket class                               | 1 = 1st, 2 = 2nd, 3 = 3rd                      |
| sex      | Sex                                        |                                                |
| Age      | Age in years                               |                                                |
| sibsp    | # of siblings / spouses aboard the Titanic |                                                |
| parch    | # of parents / children aboard the Titanic |                                                |
| ticket   | Ticket number                              |                                                |
| fare     | Passenger fare                             |                                                |
| cabin    | Cabin number                               |                                                |
| embarked | Port of Embarkation                        | C = Cherbourg, Q = Queenstown, S = Southampton |


In the following exercise you will have to get some insights about this dataset. An insight is a just derived information you can get from a dataset like the mean of age for example.

#### Exercise: Read the data `titanic_train.csv` located in the assets folder (★☆☆)

#### Exercise: File export. Export the previous data frame separated by semicolon (;) and name it as "`your_name.txt`" (★☆☆)
There are also functions to export a DataFrame to a file with different formats.

- `df.to_csv (file.csv, sep = separator, columns = Boolean, index = Boolean)`: Exports the DataFrame df to the file file.csv in CSV format using the separator string as data separator.
- `df.to_excel (file.xlsx, sheet_name = sheet, columns = Boolean, index = Boolean)`: Exports the DataFrame df to the spreadsheet sheet of the file file.xlsx in Excel format.

## Attributes of a DataFrame
There are several properties or methods for viewing the characteristics of a DataFrame.

- `df.info()`: Returns information (number of rows, number of columns, indexes, type of columns and used memory) about the DataFrame df.

- `df.shape`: Returns a tuple with the number of rows and columns of the DataFrame df.

- `df.size`: Returns the number of elements in the DataFrame.

- `df.columns`: Returns a list with the names of the columns of the DataFrame df.

- `df.index`: Returns a list with the names of the rows in the DataFrame df.

- `df.dtypes`: Returns a series with the data types of the columns of the DataFrame df.

- `df.head(n)`: Returns the first n rows of the DataFrame df.

- `df.tail(n)`: Returns the last n rows of the DataFrame df.

#### Exercise: Read the dataframe exported as "`your_name.txt`" and print all the previous attributes taking `n = 10` (★☆☆)

#### Exercise: Change the name of columns of the above data frame using two different methos (★★☆) 
Check the function `rename` (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html) and remember you can get the name of columns using `df.columns`

#### Exercise: Change the index of the above data frame using two different methos (★★☆) 
Check `iloc` (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html)

#### Exercise: Get the position (3,5) from the dataframe `your_name.txt`  (★☆☆)

#### Exercise: Get the 10-th value from the column "Ticket" from the dataframe `your_name.txt`  (★☆☆)

#### Exercise: Add columns to a DataFrame. Create a random array and a random list and add them to the dataframe coming from  `your_name.txt` (★☆☆)
The procedure for adding a new column to a DataFrame is similar to adding a new pair to a dictionary, but passing the column's values in a list or series.

#### Exercise: Create or subset a data frame. Subset the dataframe coming from `your_name.txt` by Male registers using two different methods (★★☆)
Remember the function `where` from `numpy`

## Descriptive summary of a DataFrame
As for strings, the following methods allow you to summarize the information in a DataFrame by columns:

- `df.count()`: Returns a series number of elements that are not null or NaN in each column of the DataFrame df.
- `df.sum()`: Returns a series with the sum of the data of the columns of the DataFrame df when the data is of a numeric type, or the concatenation of them when they are of the string type str.
- `df.cumsum()`: Returns a DataFrame with the cumulative sum of the data in the columns of the DataFrame df when the data is of a numeric type.
- `df.min()`: Returns a series with the minors of the data of the columns of the DataFrame df.
- `df.max()`: Returns a series with the largest of the data in the columns of the DataFrame df.
- `df.mean()`: Returns a series with the mean of the data in the columns of the DataFrame df when the data is of a numeric type.
- `df.std()`: Returns a series with the standard deviations of the data in the columns of the DataFrame df when the data is of a numeric type.
- `df.describe(include = type)`: Returns a DataFrame with a statistical summary of the columns of the DataFrame df of type type. For numerical data(number), the mean, standard deviation, minimum, maximum and quartiles of the numeric columns are calculated. For non-numeric data(object) the number of values, the number of distinct values, the mode and their frequency are calculated. If the type is not indicated, only the numeric columns are considered.

#### Exercise: Make a description of the dataset `your_name.txt` (★☆☆)

#### Exercise: Remove the column Ticket from your dataframe (★☆☆)

#### Exercise: Sort the dataframe by the Age column  (★★☆)
Check the functions `df.sort_values` and `df.sort_index`

#### Exercise: Drop the rows of your dataframe that contain na values (★★☆)

#### Exercise: Subset the rows where Age values are greater than 18 (★★☆)

#### Exercise: Subset the rows where Age values are greater than 18 and less than 5 and get the number of rows  (★★☆)

#### Exercise: Normalize the column Age (★★☆)
Remember from probability (https://en.wikipedia.org/wiki/Normalization_(statistics)) that :

$$ x_{norm} = \frac{x - \bar{x}}{\sigma}$$

#### Exercise: Consider two random array A and B, check if they are equal (★★☆)

#### Exercise: How to set the number of rows and columns displayed in the output? (★★★)
Check the function `set_option` from pandas

#### Exercise: How to join two dataframes by 2 columns so they have only the common rows? (★★★)
Join dataframes df1 and df2 by ‘fruit-pazham’ and ‘weight-kilo’.

In [ ]:
## Input

df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

#### Exercise: How to get the positions where values of two columns match? (★★★)
Join dataframes df1 and df2 by ‘fruit-pazham’ and ‘weight-kilo’.

In [ ]:
## Input
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})
